### ISSUE TITLE
exemplar support regression?

### ISSUE THREAD

**Issue by clux** [joe-elliott/tempo-otel-example#2]
Hey there, thank you for this example and talks around it. it's all been very helpful.

Short question: Has this regressed?

Have been running this code locally against a k3d deployment of tempo, but the output of the supposedly exemplare'd metric 
 `request_latency_seconds` have no metrics in http://0.0.0.0:8000/metrics when running locally.

There are also memory errors in the logs around otel, but can't remember if that was part of the demo or not:

```
2021/03/09 14:51:42 http: panic serving 127.0.0.1:52326: runtime error: invalid memory address or nil pointer dereference
goroutine 13368 [running]:
net/http.(*conn).serve.func1(0xc00017eb40)
	/usr/lib/go/src/net/http/server.go:1824 +0x153
panic(0xa8a7a0, 0xfd21f0)
	/usr/lib/go/src/runtime/panic.go:971 +0x499
go.opentelemetry.io/otel/sdk/trace.(*span).End(0xc000244780, 0x0, 0x0, 0x0)
	/home/clux/.go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.16.0/trace/span.go:229 +0x2e5
panic(0xa8a7a0, 0xfd21f0)
	/usr/lib/go/src/runtime/panic.go:965 +0x1b9
main.handler(0xc19230, 0xc00046b130, 0xc000410000)
	/home/clux/repos/tempo-otel-example/main.go:70 +0x2ea
net/http.HandlerFunc.ServeHTTP(...)
	/usr/lib/go/src/net/http/server.go:2069
main.instrumentedServer.func1(0xc19230, 0xc00046b130, 0xc000410000)
	/home/clux/repos/tempo-otel-example/main.go:149 +0x9c
net/http.HandlerFunc.ServeHTTP(0xc0001c1c40, 0xc19230, 0xc00046b130, 0xc000410000)
	/usr/lib/go/src/net/http/server.go:2069 +0x44
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP(0xc000138240, 0xc18900, 0xc00046b130, 0xc0001c5b00)
	/home/clux/.go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.16.0/handler.go:179 +0x957
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000138300, 0xc18900, 0xc0002787e0, 0xc0001c5900)
	/home/clux/.go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.serverHandler.ServeHTTP(0xc000354000, 0xc18900, 0xc0002787e0, 0xc0001c5900)
	/usr/lib/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc00017eb40, 0xc19f38, 0xc0002ea280)
	/usr/lib/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:3013 +0x39b
```

metrics output:

```
# HELP demo_request_latency_seconds Request Latency
# TYPE demo_request_latency_seconds histogram
demo_request_latency_seconds_bucket{le="0.0001"} 0
demo_request_latency_seconds_bucket{le="0.0002"} 0
demo_request_latency_seconds_bucket{le="0.0004"} 0
demo_request_latency_seconds_bucket{le="0.0008"} 0
demo_request_latency_seconds_bucket{le="0.0016"} 0
demo_request_latency_seconds_bucket{le="0.0032"} 0
demo_request_latency_seconds_bucket{le="0.0064"} 0
demo_request_latency_seconds_bucket{le="0.0128"} 0
demo_request_latency_seconds_bucket{le="0.0256"} 0
demo_request_latency_seconds_bucket{le="0.0512"} 0
demo_request_latency_seconds_bucket{le="0.1024"} 41
demo_request_latency_seconds_bucket{le="0.2048"} 63
demo_request_latency_seconds_bucket{le="0.4096"} 78
demo_request_latency_seconds_bucket{le="0.8192"} 102
demo_request_latency_seconds_bucket{le="1.6384"} 109
demo_request_latency_seconds_bucket{le="3.2768"} 115
demo_request_latency_seconds_bucket{le="6.5536"} 122
demo_request_latency_seconds_bucket{le="13.1072"} 130
demo_request_latency_seconds_bucket{le="26.2144"} 130
demo_request_latency_seconds_bucket{le="52.4288"} 130
demo_request_latency_seconds_bucket{le="104.8576"} 130
demo_request_latency_seconds_bucket{le="209.7152"} 130
demo_request_latency_seconds_bucket{le="419.4304"} 130
demo_request_latency_seconds_bucket{le="838.8608"} 130
demo_request_latency_seconds_bucket{le="1677.7216"} 130
demo_request_latency_seconds_bucket{le="3355.4432"} 130
demo_request_latency_seconds_bucket{le="6710.8864"} 130
demo_request_latency_seconds_bucket{le="13421.7728"} 130
demo_request_latency_seconds_bucket{le="26843.5456"} 130
demo_request_latency_seconds_bucket{le="53687.0912"} 130
demo_request_latency_seconds_bucket{le="107374.1824"} 130
demo_request_latency_seconds_bucket{le="214748.3648"} 130
demo_request_latency_seconds_bucket{le="429496.7296"} 130
demo_request_latency_seconds_bucket{le="858993.4592"} 130
demo_request_latency_seconds_bucket{le="1.7179869184e+06"} 130
demo_request_latency_seconds_bucket{le="3.4359738368e+06"} 130
demo_request_latency_seconds_bucket{le="6.8719476736e+06"} 130
demo_request_latency_seconds_bucket{le="1.37438953472e+07"} 130
demo_request_latency_seconds_bucket{le="2.74877906944e+07"} 130
demo_request_latency_seconds_bucket{le="5.49755813888e+07"} 130
demo_request_latency_seconds_bucket{le="1.099511627776e+08"} 130
demo_request_latency_seconds_bucket{le="2.199023255552e+08"} 130
demo_request_latency_seconds_bucket{le="4.398046511104e+08"} 130
demo_request_latency_seconds_bucket{le="8.796093022208e+08"} 130
demo_request_latency_seconds_bucket{le="1.7592186044416e+09"} 130
demo_request_latency_seconds_bucket{le="3.5184372088832e+09"} 130
demo_request_latency_seconds_bucket{le="7.0368744177664e+09"} 130
demo_request_latency_seconds_bucket{le="1.40737488355328e+10"} 130
demo_request_latency_seconds_bucket{le="2.81474976710656e+10"} 130
demo_request_latency_seconds_bucket{le="5.62949953421312e+10"} 130
demo_request_latency_seconds_bucket{le="+Inf"} 130
demo_request_latency_seconds_sum 150.66746893099995
demo_request_latency_seconds_count 130
```

**Comment by joe-elliott** [comment]
I just ran through the full demo and aside from a few minor tweaks:

https://github.com/joe-elliott/tempo-otel-example/commit/78385907c0e6c3382e499cb336e9e4b296931780

everything worked.  I am definitely not seeing a panic and I am seeing exemplars.  Does that panic occur when you `curl http://localhost:8000` ?

**Comment by clux** [comment]
Hm, that's strange, it' the same in docker or not, no exemplars. I am building with go 1.16.2.

Found out that the panic can happen when you spam requests to `/` via chrome and cancel some of them, it's not really something to worry about. Doesn't happen via `curl`
